### ISSUE TITLE
pip install flute-kernel

### ISSUE THREAD

**Issue by LiMa-cas** [HanGuo97/flute#5] opened 2024-08-16 05:46 UTC
Hi，when I use pip install flute-kernel， there are errors：‘pip install flute-kernel
ERROR: Could not find a version that satisfies the requirement flute-kernel (from versions: none)
ERROR: No matching distribution found for flute-kernel’，thanks a lot

**Comment by HanGuo97** [comment] 2024-08-16 19:20
Hi, thanks for trying it out!

This happens if you use a combination of OS, Python version, etc that we didn't build FLUTE with. Do you mind elaborating what your OS and Python version are?

**Comment by LiMa-cas** [comment] 2024-08-17 06:50
thanks，problems sloved！

**Comment by HanGuo97** [comment] 2024-08-17 14:32
Great, glad it works!

As for your question, did you git clone the FLUTE repo? This might be caused by the system recognizing the base directory `flute` as the package. If that's the case, you can try running the script in a different directory, or run it inside the `flute/` directory.

**Comment by LiMa-cas** [comment] 2024-08-19 03:38
thanks.problems solved. but it seems that the limitations of torch is not right, the problems is 
'WARNING 08-19 11:35:53 _core_ext.py:180] Failed to import from vllm._core_C with ImportError('/extra_data/cutlass/flute/flute/vllm/vllm/_core_C.abi3.so: undefined symbol: _ZNK3c105Error4whatEv')
Traceback (most recent call last):
  File "/extra_data/miniconda3/envs/flute/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/extra_data/miniconda3/envs/flute/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/extra_data/miniconda3/envs/flute/lib/python3.10/site-packages/flute/__init__.py", line 5, in <module>
    from vllm.platforms import current_platform
  File "/extra_data/cutlass/flute/flute/vllm/vllm/__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/extra_data/cutlass/flute/flute/vllm/vllm/engine/arg_utils.py", line 9, in <module>
    from vllm.config import (CacheConfig, DecodingConfig, DeviceConfig,
  File "/extra_data/cutlass/flute/flute/vllm/vllm/config.py", line 12, in <module>
    from vllm.model_executor.layers.quantization import QUANTIZATION_METHODS
  File "/extra_data/cutlass/flute/flute/vllm/vllm/model_executor/layers/quantization/__init__.py", line 3, in <module>
    from vllm.model_executor.layers.quantization.aqlm import AQLMConfig
  File "/extra_data/cutlass/flute/flute/vllm/vllm/model_executor/layers/quantization/aqlm.py", line 11, in <module>
    from vllm import _custom_ops as ops
  File "/extra_data/cutlass/flute/flute/vllm/vllm/_custom_ops.py", line 7, in <module>
    from vllm._core_ext import ScalarType
  File "/extra_data/cutlass/flute/flute/vllm/vllm/_core_ext.py", line 182, in <module>
    ScalarType = torch.classes._core_C.ScalarType
  File "/extra_data/miniconda3/envs/flute/lib/python3.10/site-packages/torch/_classes.py", line 12, in __getattr__
    proxy = torch._C._get_custom_class_python_wrapper(self.name, attr)
RuntimeError: Tried to instantiate class '_core_C.ScalarType', but it does not exist! Ensure that it is registered via torch::class_'
here is my pip list:
'Package                           Version
--------------------------------- ------------
accelerate                        0.33.0
aiohappyeyeballs                  2.3.6
aiohttp                           3.10.3
aiosignal                         1.3.1
annotated-types                   0.7.0
anyio                             4.4.0
async-timeout                     4.0.3
attrs                             24.2.0
audioread                         3.0.1
certifi                           2024.7.4
cffi                              1.17.0
charset-normalizer                3.3.2
click                             8.1.7
cloudpickle                       3.0.0
cmake                             3.30.2
contourpy                         1.2.1
cycler                            0.12.1
datasets                          2.21.0
decorator                         5.1.1
dill                              0.3.8
diskcache                         5.6.3
distro                            1.9.0
exceptiongroup                    1.2.2
fastapi                           0.112.1
filelock                          3.13.1
flute-kernel                      0.0.6
fonttools                         4.53.1
frozenlist                        1.4.1
fsspec                            2024.2.0
gguf                              0.9.1
h11                               0.14.0
httpcore                          1.0.5
httptools                         0.6.1
httpx                             0.27.0
huggingface-hub                   0.24.5
idna                              3.7
importlib_metadata                8.2.0
interegular                       0.3.3
jaxtyping                         0.2.33
Jinja2                            3.1.3
jiter                             0.5.0
joblib                            1.4.2
jsonschema                        4.23.0
jsonschema-specifications         2023.12.1
kiwisolver                        1.4.5
lark                              1.2.2
lazy_loader                       0.4
librosa                           0.10.2.post1
llvmlite                          0.43.0
lm-format-enforcer                0.10.3
MarkupSafe                        2.1.5
matplotlib                        3.9.2
mpmath                            1.3.0
msgpack                           1.0.8
msgspec                           0.18.6
multidict                         6.0.5
multiprocess                      0.70.16
nest-asyncio                      1.6.0
networkx                          3.2.1
ninja                             1.11.1.1
numba                             0.60.0
numpy                             1.26.3
nvidia-cublas-cu12                12.1.3.1
nvidia-cuda-cupti-cu12            12.1.105
nvidia-cuda-nvrtc-cu12            12.1.105
nvidia-cuda-runtime-cu12          12.1.105
nvidia-cudnn-cu12                 8.9.2.26
nvidia-cufft-cu12                 11.0.2.54
nvidia-curand-cu12                10.3.2.106
nvidia-cusolver-cu12              11.4.5.107
nvidia-cusparse-cu12              12.1.0.106
nvidia-ml-py                      12.560.30
nvidia-nccl-cu12                  2.20.5
nvidia-nvjitlink-cu12             12.1.105
nvidia-nvtx-cu12                  12.1.105
openai                            1.41.0
outlines                          0.0.46
packaging                         24.1
pandas                            2.2.2
pillow                            10.2.0
pip                               24.2
platformdirs                      4.2.2
pooch                             1.8.2
prometheus_client                 0.20.0
prometheus-fastapi-instrumentator 7.0.0
protobuf                          5.27.3
psutil                            6.0.0
py-cpuinfo                        9.0.0
pyairports                        2.1.1
pyarrow                           17.0.0
pycountry                         24.6.1
pycparser                         2.22
pydantic                          2.8.2
pydantic_core                     2.20.1
pyparsing                         3.1.2
python-dateutil                   2.9.0.post0
python-dotenv                     1.0.1
pytz                              2024.1
PyYAML                            6.0.2
pyzmq                             26.1.0
ray                               2.34.0
referencing                       0.35.1
regex                             2024.7.24
requests                          2.32.3
rpds-py                           0.20.0
safetensors                       0.4.4
scikit-learn                      1.5.1
scipy                             1.14.0
sentencepiece                     0.2.0
setuptools                        72.1.0
six                               1.16.0
sniffio                           1.3.1
soundfile                         0.12.1
soxr                              0.4.0
starlette                         0.38.2
sympy                             1.12
threadpoolctl                     3.5.0
tiktoken                          0.7.0
tokenizers                        0.19.1
torch                             2.3.1+cu121
torchaudio                        2.3.1+cu121
torchvision                       0.18.1+cu121
tqdm                              4.66.5
transformers                      4.44.0
triton                            2.3.1
typeguard                         2.13.3
typing_extensions                 4.12.2
tzdata                            2024.1
urllib3                           2.2.2
uvicorn                           0.30.6
uvloop                            0.20.0
vllm                              0.5.4
vllm-flash-attn                   2.6.1
watchfiles                        0.23.0
websockets                        12.0
wheel                             0.43.0
xformers                          0.0.27.post2
xxhash                            3.4.1
yarl                              1.9.4
zipp                              3.20.0'

**Comment by HanGuo97** [comment] 2024-08-19 13:55
Thanks for the follow-up, and glad that the problem is solved.

Do you might elaborate what you meant by the following sentence? (I don't think I got what you were trying to say)
> but it seems that the limitations of torch is not right

**Comment by HanGuo97** [comment] 2024-08-20 01:56
That's interesting, and very good to know. Thanks! I think FLUTE is compiled against `torch==2.3.1`, whereas vLLM might be using `torch==2.4.0`. I didn't expect the version to make any difference, but perhaps it did. In the next version of FLUTE (in a few days), we will bump the version to 2.4.0 as well. Good feedback!

I'm going to close this issue for now as I assume it's fixed. Feel free to re-open if you wish.

**Closed by HanGuo97** 2024-08-20 01:56 UTC

**Comment by LiMa-cas** [comment] 2024-08-20 02:37
sorry,but I could not run succesfully, could u help slove the problems?

**Comment by HanGuo97** [comment] 2024-08-20 03:09
Ah I thought it got fixed.

The error message seems to come from this line `from vllm.platforms import current_platform`. This seems more like a vLLM issue? Perhaps try reinstalling vLLM?

**Comment by LiMa-cas** [comment] 2024-08-20 03:21
I have reinstalled, but it still failed. which version do u have? the pip list is above.

**Comment by HanGuo97** [comment] 2024-08-20 03:25
I have `0.5.3.post1`
